### PR TITLE
I should stop making many changes

### PR DESCRIPTION
**Pull request by Joakim-droid**
Edited the dashboard,  log-in and log-out should work properly now.

### CODE REVIEW

**Comment by b24177** [comment]
Looks good! What do you think about adding Current to the Navbar so that it shows on all pages? We could add a logo there later as well.
Screenshot 2020-09-06 at 12 37 07

Also, please correct the spelling of Available in the Navbar.

**Comment by Joakim-droid** [comment]
A logo would be great. Yeah, I should have looked up how available is spelled lol.

**Comment by b24177** [comment]
Shall I approve this for now?

**Comment by Joakim-droid** [comment]
I'm still doing some styling with the navbar, give me a few minutes.

**Review by b24177 — APPROVED** [review]

**Pull request merged**
