### PR TITLE
Layout changes to car index page

### PR DESCRIPTION
**Pull request by b24177**
When the page is zoomed in to 90%, the cards have proper spacing. Suggestions on how to make it look good at 100%?

### CODE REVIEW

**Comment by Joakim-droid** [comment]
Do you have any screenshots of the improvements?

**Comment by b24177** [comment]
Screenshot 2020-09-06 at 13 35 34

**Comment by Joakim-droid** [comment]
Looking good! Is this 90%?

**Comment by b24177** [comment]
Yes. Here is 100%:
Screenshot 2020-09-06 at 13 37 30

**Comment by Joakim-droid** [comment]
Correct me if I'm wrong, but why doesn't the margin work when it's 100%? Could it be the width of the cards?

**Comment by b24177** [comment]
I can't seem to figure it out :/ 

By the way, how about I also add titles to the data on the cards, and add in dollars as a default for now? In case we don't end up adding support for currency.
Screenshot 2020-09-06 at 13 40 45

**Comment by Joakim-droid** [comment]
That's a good idea with the titles. Have you tried to make the cards smaller?

**Comment by b24177** [comment]
With my current structure, w-75 seems to be the breaking point. If I bump it up to 80 it does nothing at 100%.
Screenshot 2020-09-06 at 13 53 15

**Comment by b24177** [comment]
@Joakim-droid, I am just sticking to the changes to the data display within the cards for now, along with the margins between the cards. Need to figure out how to fix the width of the cards, but can you approve these changes in the meantime? I will open a new branch for the width later on.

**Pull request merged**
